/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cenfotec.componentes.mastermind;

import java.awt.event.ActionEvent;
import java.util.*;

/**
 *
 * @author kamil
 */
public class Mastermind extends javax.swing.JPanel {

    /**
     * Creates new form Mastermind
     */
    
    char[] respuesta = new char[4];
    boolean termino = false;
    boolean gano = false;
    int intentos = 0;
    
    public Mastermind() {
        initComponents();
        reiniciar.setVisible(false);
        oportunidades.setVisible(false);
        intento.setVisible(false);
        parciales.setVisible(false);
        totales.setVisible(false);
        estado.setVisible(false);
        jugar.setVisible(true);
        label.setVisible(false);
        enviarIntento.setVisible(false);
        trampa.setVisible(false);
    }

    
    
    public char[] generarColores(){
       char[] respuesta = new char[4];
       String[] opciones = {"A","R","B","N","V","M"};
       List<String> temp = Arrays.asList(opciones);
       Collections.shuffle(temp);
       opciones = temp.toArray(new String[temp.size()]);
       for(int i = 0; i<4; i++){
        respuesta[i] = opciones[i].charAt(0);
       }
       return respuesta;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor. 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        oportunidades = new javax.swing.JLabel();
        intento = new javax.swing.JTextField();
        enviarIntento = new javax.swing.JToggleButton();
        parciales = new javax.swing.JLabel();
        totales = new javax.swing.JLabel();
        estado = new javax.swing.JLabel();
        trampa = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        reiniciar = new javax.swing.JToggleButton();
        jugar = new javax.swing.JToggleButton();

        oportunidades.setText("Oportunidades: 0/8");

        intento.setToolTipText("Intento");

        enviarIntento.setText("Enviar intento");
        enviarIntento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarIntentoActionPerformed(evt);
            }
        });

        parciales.setText("Aciertos Parciales: 0");

        totales.setText("Aciertos Totales: 0");

        estado.setText("Estado:");

        trampa.setText("Trampa: ");

        label.setText("[A, R, B, N, V, M]");

        reiniciar.setEnabled(false);
        reiniciar.setLabel("Reiniciar");
        reiniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reiniciarMouseClicked(evt);
            }
        });

        jugar.setText("Jugar");
        jugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jugarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(oportunidades)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jugar))
                            .addComponent(reiniciar)
                            .addComponent(parciales)
                            .addComponent(totales)
                            .addComponent(label)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(intento, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(enviarIntento))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(estado))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(trampa)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jugar)
                    .addComponent(oportunidades))
                .addGap(17, 17, 17)
                .addComponent(label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enviarIntento))
                .addGap(18, 18, 18)
                .addComponent(parciales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totales)
                .addGap(18, 18, 18)
                .addComponent(reiniciar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(estado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(trampa)
                .addGap(39, 39, 39))
        );

        reiniciar.getAccessibleContext().setAccessibleName("reiniciar");
        reiniciar.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void enviarIntentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarIntentoActionPerformed

        if(intento.getText().length() == 4){
            estado.setText("Estado: ");
            intentos++;
            oportunidades.setText("Oportunidades " + intentos + "/8");
            revisar();
        }else{
            estado.setText("Estado: Intento incorrecto");
        }
        
    }//GEN-LAST:event_enviarIntentoActionPerformed

    private void reiniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reiniciarMouseClicked
        reiniciarJuego();
    }//GEN-LAST:event_reiniciarMouseClicked

    private void jugarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jugarMouseClicked
       
        reiniciar.setVisible(false);
        oportunidades.setVisible(true);
        intento.setVisible(true);
        parciales.setVisible(true);
        totales.setVisible(true);
        estado.setVisible(true);
        jugar.setVisible(false);
        label.setVisible(true);
        enviarIntento.setVisible(true);
        trampa.setVisible(true);
        respuesta = generarColores();
        
        //Para testing
        trampa.setVisible(false);
        trampa.setText(Arrays.toString(respuesta));
        
    }//GEN-LAST:event_jugarMouseClicked
    
    public void revisar(){
        char[] intentoRevisar = intento.getText().toUpperCase().toCharArray();
        int iParciales = 0;
        int iTotales = 0;
        for(int i = 0; i<4; i++){
            
            if(intentoRevisar[i] == respuesta[i]){
                iTotales++;
                continue;
            }
            
            for(int k = 0; k<4; k++){
                if(intentoRevisar[i] == respuesta[k]){
                    iParciales++;
                }
            }
            
            
        }
        
        parciales.setText("Aciertos Parciales: " + iParciales);
        totales.setText("Aciertos Totales: " + iTotales);
        if(iTotales == 4){
            gano();
        }
        if(intentos == 8 && !gano){
            perdio();
        }
    }

    public void reiniciarJuego(){
        termino = false;
        gano = false;
        respuesta = generarColores();
        trampa.setText(Arrays.toString(respuesta));
        intentos = 0;
        oportunidades.setText("Oportunidades " + intentos + "/8");
        parciales.setText("Aciertos Parciales: " + 0);
        totales.setText("Aciertos Totales: " + 0);
        estado.setText("Estado: ");
        enviarIntento.setEnabled(true);
        intento.setEditable(true);
        reiniciar.setVisible(false);
        reiniciar.setEnabled(false);
    }
    
    public void gano(){
        termino = true;
        gano = true;
        estado.setText("Estado: Ganó");
        enviarIntento.setEnabled(false);
        intento.setEditable(false);
        reiniciar.setVisible(true);
        reiniciar.setEnabled(true);
    }
    
    public void perdio(){
        termino = true;
        gano = false;
        estado.setText("Estado: Perdió");
        enviarIntento.setEnabled(false);
        intento.setEditable(false);
        reiniciar.setVisible(true);
        reiniciar.setEnabled(true);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton enviarIntento;
    private javax.swing.JLabel estado;
    private javax.swing.JTextField intento;
    private javax.swing.JToggleButton jugar;
    private javax.swing.JLabel label;
    private javax.swing.JLabel oportunidades;
    private javax.swing.JLabel parciales;
    private javax.swing.JToggleButton reiniciar;
    private javax.swing.JLabel totales;
    private javax.swing.JLabel trampa;
    // End of variables declaration//GEN-END:variables
}
